#!/bin/sh

echo "设置用户 chrono 为 ${CHRONO_UID}:${CHRONO_GID}"
usermod -o -u ${CHRONO_UID} chrono
groupmod -o -g ${CHRONO_GID} chrono || true
usermod -g ${CHRONO_GID} chrono

echo "设置 UMASK 为 ${CHRONO_UMASK}"
umask ${CHRONO_UMASK}

echo "设置用户文件夹所有者"
chown -R ${CHRONO_UID}:${CHRONO_GID} /chrono /llqqnt

echo "设置用户文件夹权限"
chmod -R 755 /chrono /llqqnt
